-- Encargados de comercial: supervisores que reciben copia oculta (BCC) en confirmacion de pedido.
-- Gestion: Panel de Control de la app (rol ADMINISTRADOR, JWT es_administrador).
-- Ejecutar en Supabase SQL Editor.

CREATE TABLE IF NOT EXISTS public.comerciales_encargados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comercial_numero INTEGER NOT NULL REFERENCES public.usuarios_comerciales(numero) ON DELETE CASCADE,
    encargado_usuario_id INTEGER NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT comerciales_encargados_unique UNIQUE (comercial_numero, encargado_usuario_id)
);

CREATE INDEX IF NOT EXISTS idx_comerciales_encargados_comercial_numero
    ON public.comerciales_encargados (comercial_numero);

CREATE INDEX IF NOT EXISTS idx_comerciales_encargados_encargado_usuario_id
    ON public.comerciales_encargados (encargado_usuario_id);

COMMENT ON TABLE public.comerciales_encargados IS
'Encargados que supervisan un comercial; reciben BCC en emails de confirmacion de pedido de sus clientes.';

COMMENT ON COLUMN public.comerciales_encargados.comercial_numero IS
'Numero del comercial (usuarios_comerciales.numero).';

COMMENT ON COLUMN public.comerciales_encargados.encargado_usuario_id IS
'Usuario encargado (COMERCIAL, DEPENDIENTE o ADMINISTRADOR en usuarios.tipo).';

CREATE OR REPLACE FUNCTION public.set_comerciales_encargados_fecha_actualizacion()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.fecha_actualizacion := NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_set_comerciales_encargados_fecha_actualizacion ON public.comerciales_encargados;
CREATE TRIGGER trg_set_comerciales_encargados_fecha_actualizacion
BEFORE UPDATE ON public.comerciales_encargados
FOR EACH ROW
EXECUTE FUNCTION public.set_comerciales_encargados_fecha_actualizacion();

CREATE OR REPLACE FUNCTION public.validate_comercial_encargado()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_tipo TEXT;
BEGIN
    SELECT UPPER(TRIM(COALESCE(tipo, '')))
    INTO v_tipo
    FROM public.usuarios
    WHERE id = NEW.encargado_usuario_id;

    IF v_tipo IS NULL OR v_tipo = '' THEN
        RAISE EXCEPTION 'El encargado debe existir en usuarios';
    END IF;

    IF v_tipo NOT IN ('COMERCIAL', 'DEPENDIENTE', 'ADMINISTRADOR') THEN
        RAISE EXCEPTION 'El encargado debe ser COMERCIAL, DEPENDIENTE o ADMINISTRADOR';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM public.usuarios_comerciales uc
        WHERE uc.numero = NEW.comercial_numero
          AND uc.usuario_id = NEW.encargado_usuario_id
    ) THEN
        RAISE EXCEPTION 'Un comercial no puede ser encargado de si mismo';
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_validate_comercial_encargado ON public.comerciales_encargados;
CREATE TRIGGER trg_validate_comercial_encargado
BEFORE INSERT OR UPDATE ON public.comerciales_encargados
FOR EACH ROW
EXECUTE FUNCTION public.validate_comercial_encargado();

ALTER TABLE public.comerciales_encargados ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS comerciales_encargados_select_admin ON public.comerciales_encargados;
DROP POLICY IF EXISTS comerciales_encargados_insert_admin ON public.comerciales_encargados;
DROP POLICY IF EXISTS comerciales_encargados_update_admin ON public.comerciales_encargados;
DROP POLICY IF EXISTS comerciales_encargados_delete_admin ON public.comerciales_encargados;

CREATE POLICY comerciales_encargados_select_admin
    ON public.comerciales_encargados
    FOR SELECT
    TO authenticated
    USING (
        COALESCE(((auth.jwt() -> 'app_metadata') ->> 'es_administrador')::boolean, false) IS TRUE
    );

CREATE POLICY comerciales_encargados_insert_admin
    ON public.comerciales_encargados
    FOR INSERT
    TO authenticated
    WITH CHECK (
        COALESCE(((auth.jwt() -> 'app_metadata') ->> 'es_administrador')::boolean, false) IS TRUE
    );

CREATE POLICY comerciales_encargados_update_admin
    ON public.comerciales_encargados
    FOR UPDATE
    TO authenticated
    USING (
        COALESCE(((auth.jwt() -> 'app_metadata') ->> 'es_administrador')::boolean, false) IS TRUE
    )
    WITH CHECK (
        COALESCE(((auth.jwt() -> 'app_metadata') ->> 'es_administrador')::boolean, false) IS TRUE
    );

CREATE POLICY comerciales_encargados_delete_admin
    ON public.comerciales_encargados
    FOR DELETE
    TO authenticated
    USING (
        COALESCE(((auth.jwt() -> 'app_metadata') ->> 'es_administrador')::boolean, false) IS TRUE
    );

GRANT SELECT, INSERT, UPDATE, DELETE ON public.comerciales_encargados TO authenticated;
GRANT ALL ON public.comerciales_encargados TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.comerciales_encargados_id_seq TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.comerciales_encargados_id_seq TO service_role;
