-- Pactos de descuento por cliente para sobrescribir tarifa base por clave_descuento.
-- Caso de uso:
--   tarifa base cliente = 30%
--   pacto cliente para clave 02 = 32%
--   => en app se aplica 32% para productos con clave_descuento = '02'

CREATE TABLE IF NOT EXISTS public.pactos_clientes_descuento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_cliente INTEGER NOT NULL,
    clave_descuento TEXT NOT NULL,
    descuento_pct NUMERIC(6,2) NOT NULL CHECK (descuento_pct >= 0 AND descuento_pct <= 1000),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pactos_cliente_clave_unique UNIQUE (codigo_cliente, clave_descuento)
);

CREATE INDEX IF NOT EXISTS idx_pactos_clientes_descuento_codigo_cliente
    ON public.pactos_clientes_descuento (codigo_cliente);

CREATE INDEX IF NOT EXISTS idx_pactos_clientes_descuento_clave
    ON public.pactos_clientes_descuento (clave_descuento);

CREATE OR REPLACE FUNCTION public.set_pactos_clientes_descuento_fecha_actualizacion()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.fecha_actualizacion := NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_set_pactos_clientes_descuento_fecha_actualizacion ON public.pactos_clientes_descuento;
CREATE TRIGGER trg_set_pactos_clientes_descuento_fecha_actualizacion
BEFORE UPDATE ON public.pactos_clientes_descuento
FOR EACH ROW
EXECUTE FUNCTION public.set_pactos_clientes_descuento_fecha_actualizacion();

ALTER TABLE public.pactos_clientes_descuento ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS pactos_clientes_descuento_select_anon ON public.pactos_clientes_descuento;
DROP POLICY IF EXISTS pactos_clientes_descuento_insert_anon ON public.pactos_clientes_descuento;
DROP POLICY IF EXISTS pactos_clientes_descuento_update_anon ON public.pactos_clientes_descuento;

CREATE POLICY pactos_clientes_descuento_select_anon
    ON public.pactos_clientes_descuento
    FOR SELECT
    USING (true);

CREATE POLICY pactos_clientes_descuento_insert_anon
    ON public.pactos_clientes_descuento
    FOR INSERT
    WITH CHECK (true);

CREATE POLICY pactos_clientes_descuento_update_anon
    ON public.pactos_clientes_descuento
    FOR UPDATE
    USING (true)
    WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE ON public.pactos_clientes_descuento TO anon;
GRANT ALL ON public.pactos_clientes_descuento TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.pactos_clientes_descuento_id_seq TO anon;
GRANT USAGE, SELECT ON SEQUENCE public.pactos_clientes_descuento_id_seq TO service_role;
